[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_program = "6s3hagqqXdAggtmsoyEoeCVaWdipogNGBu8puDyoneKV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/hodinhtuankiet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

