[toolchain]

[features]
resolution = true
skip-lint = false

[build]
program-name = "todo_app"

[programs.devnet]
todo_app = "7G2a6sfs9tYCyYVmDS5JfUwBX9Cc3fGs9b1uENhrbUQd"

[programs.localnet]
todo_app = "7G2a6sfs9tYCyYVmDS5JfUwBX9Cc3fGs9b1uENhrbUQd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-profile.ts"
